---
- name: "Check for wine binary"
  ansible.builtin.stat:
    path: '/usr/bin/wine'
  changed_when: false
  register: wine_install

- name: "Install tasks"
  when: not wine_install.stat.exists or wine_force_install|bool
  block:
    - name: "Add i386 support for dpkg"
      ansible.builtin.lineinfile:
        dest: /var/lib/dpkg/arch
        line: "i386"
        create: true
        mode: 0644

    - name: "Install requirement"
      ansible.builtin.package:
        name: [gnupg2, ca-certificates, apt-transport-https, software-properties-common, unzip, tar, bzip2]
        state: present

    - name: "Add winehq apt key"
      ansible.builtin.apt_key:
        url: https://dl.winehq.org/wine-builds/winehq.key
        state: present

    - name: Add winhq repo
      ansible.builtin.apt_repository:
        repo: "deb https://dl.winehq.org/wine-builds/{{ ansible_distribution | lower }}/ {{ ansible_distribution_release }} main"
        state: present
        filename: winehq

    - name: "Install winehq"
      ansible.builtin.package:
        name: winehq-stable
        update_cache: true
        install_recommends: true
        state: present

    - name: "Creates wine directory"
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: 0755
      with_items:
        - /opt/wine-stable/share/wine/mono/
        - /opt/wine-stable/share/wine/gecko/

    - name: "Download mono and gecko globally"
      ansible.builtin.unarchive:
        src: "http://dl.winehq.org/wine/{{ item.file }}"
        dest: "/opt/wine-stable/share/wine/{{ item.folder }}"
        remote_src: true
      with_items:
        - {file: "wine-gecko/2.47.1/wine-gecko-2.47.1-x86.tar.bz2", folder: gecko}
        - {file: "wine-gecko/2.47.1/wine-gecko-2.47.1-x86_64.tar.bz2", folder: gecko}
        - {file: "wine-mono/5.1.1/wine-mono-5.1.1-x86.tar.xz", folder: mono}
        - {file: "wine-mono/4.9.4/wine-mono-4.9.4.tar.gz", folder: mono}
